import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const componentPath = new URL('../src/components/gateway/GatewayPriorityDialog.vue', import.meta.url)
const hostPath = new URL('../src/components/gateway/GatewayOverlayHost.vue', import.meta.url)

test('gateway priority dialog declares the priority editing UI contract', async () => {
  const source = await readFile(componentPath, 'utf8')

  assert.match(source, /const open = defineModel<boolean>\('open'/)
  assert.match(source, /const insertIndex = defineModel<number \| undefined>\('insertIndex'/)
  assert.match(source, /columns: ColumnsType<GatewayRoute>/)
  assert.match(source, /routes: GatewayRoute\[\]/)
  assert.match(source, /selectedRoute: GatewayRoute \| null/)
  assert.match(source, /rowClassName: \(record: GatewayRoute\) => string/)
  assert.match(source, /'move'/)
  assert.match(source, /'preset'/)
  assert.match(source, /<a-modal/)
  assert.match(source, /v-model:open="open"/)
  assert.match(source, /title="设置优先权"/)
  assert.match(source, /width="920px"/)
  assert.match(source, /:footer="null"/)
  assert.match(source, /<a-spin :spinning="loading"/)
  assert.match(source, /class="priority-dialog"/)
  assert.match(source, /:columns="columns"/)
  assert.match(source, /:data-source="routes"/)
  assert.match(source, /:pagination="\{ pageSize: 8 \}"/)
  assert.match(source, /:row-key="rowKey"/)
  assert.match(source, /:row-class-name="rowClassName"/)
  assert.match(source, /<GatewayRouteTextCell mode="priority"/)
  assert.match(source, /<GatewayRouteTextCell mode="group"/)
  assert.match(source, /当前路由/)
  assert.match(source, /routePriorityLabel\(selectedRoute\)/)
  assert.match(source, /v-model:value="insertIndex"/)
  assert.match(source, /:max="Math\.max\(routes\.length - 1, 0\)"/)
  assert.match(source, /@click="\$emit\('move'\)"/)
  assert.match(source, /@click="\$emit\('preset', 'package'\)"/)
  assert.match(source, /@click="\$emit\('preset', 'balance'\)"/)
})

test('GatewayOverlayHost delegates priority dialog rendering to the component boundary', async () => {
  const source = await readFile(hostPath, 'utf8')

  assert.match(source, /import GatewayPriorityDialog from '\.\/GatewayPriorityDialog\.vue'/)
  assert.match(source, /<GatewayPriorityDialog/)
  assert.match(source, /v-model:open="priorityOpen"/)
  assert.match(source, /v-model:insert-index="priorityInsertIndex"/)
  assert.match(source, /:loading="priorityLoading"/)
  assert.match(source, /:columns="priorityColumns"/)
  assert.match(source, /:routes="priorityRoutes"/)
  assert.match(source, /:selected-route="prioritySelectedRoute"/)
  assert.match(source, /:row-key="routeRowKey"/)
  assert.match(source, /:row-class-name="priorityRowClassName"/)
  assert.match(source, /@move="emit\('priority-move'\)"/)
  assert.match(source, /@preset="emit\('priority-preset', \$event\)"/)
  assert.doesNotMatch(source, /<a-modal\s+v-model:open="priorityOpen"/)
  assert.doesNotMatch(source, /<div class="priority-dialog">/)
  assert.doesNotMatch(source, /priorityRoutes\.length - 1/)
})
