import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const componentPath = new URL('../src/components/gateway/GatewayRouteManagementToolbar.vue', import.meta.url)
const pagePath = new URL('../src/components/gateway/GatewayRouteManagementPage.vue', import.meta.url)

test('gateway route management toolbar declares the route toolbar UI contract', async () => {
  const source = await readFile(componentPath, 'utf8')

  assert.match(source, /filteredRouteCount: number/)
  assert.match(source, /routeCount: number/)
  assert.match(source, /requestUrl: string/)
  assert.match(source, /codexTooltip: string/)
  assert.match(source, /maskedApiKey: string/)
  assert.match(source, /hasApiKey: boolean/)
  assert.match(source, /probeAllProgress: RouteBatchProgress \| null/)
  assert.match(source, /balanceProbeAllProgress: RouteBatchProgress \| null/)
  assert.match(source, /event: 'copy-request-url'/)
  assert.match(source, /event: 'copy-api-key'/)
  assert.match(source, /event: 'refresh'/)
  assert.match(source, /event: 'sync'/)
  assert.match(source, /event: 'probe-all'/)
  assert.match(source, /event: 'update-all-balances'/)
  assert.match(source, /event: 'disable-all'/)
  assert.match(source, /event: 'manage-groups'/)
  assert.match(source, /event: 'add-upstream'/)
  assert.match(source, /event: 'open-settings'/)
  assert.match(source, /class="page-toolbar page-toolbar--actions"/)
  assert.match(source, /class="route-management-toolbar"/)
  assert.match(source, /class="route-management-heading"/)
  assert.match(source, /<GatewayAccessBar/)
  assert.match(source, /variant="route"/)
  assert.match(source, /<GatewayRouteBatchAction/)
  assert.match(source, /label="探测全部"/)
  assert.match(source, /label="更新余额"/)
  assert.match(source, /禁用全部/)
  assert.match(source, /路由分组/)
  assert.match(source, /添加上游/)
  assert.match(source, /网关策略/)
  assert.match(source, /ReloadOutlined/)
  assert.match(source, /SyncOutlined/)
  assert.match(source, /PlusOutlined/)
  assert.match(source, /SettingOutlined/)
})

test('GatewayRouteManagementPage delegates route management toolbar rendering to the component boundary', async () => {
  const source = await readFile(pagePath, 'utf8')

  assert.match(source, /import GatewayRouteManagementToolbar from '\.\/GatewayRouteManagementToolbar\.vue'/)
  assert.match(source, /<GatewayRouteManagementToolbar/)
  assert.match(source, /:filtered-route-count="filteredRouteCount"/)
  assert.match(source, /@refresh="emit\('refresh'\)"/)
  assert.match(source, /@sync="emit\('sync'\)"/)
  assert.match(source, /@probe-all="emit\('probe-all'\)"/)
  assert.match(source, /@update-all-balances="emit\('update-all-balances'\)"/)
  assert.match(source, /@disable-all="emit\('disable-all'\)"/)
  assert.match(source, /@manage-groups="emit\('manage-groups'\)"/)
  assert.match(source, /@add-upstream="emit\('add-upstream'\)"/)
  assert.match(source, /@open-settings="emit\('open-settings'\)"/)
  assert.doesNotMatch(source, /<div v-else class="route-management-toolbar">/)
  assert.doesNotMatch(source, /label="探测全部"/)
  assert.doesNotMatch(source, /label="更新余额"/)
  assert.doesNotMatch(source, /添加上游/)
})
