import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const componentPath = new URL('../src/components/gateway/GatewaySettingsDialog.vue', import.meta.url)
const hostPath = new URL('../src/components/gateway/GatewayOverlayHost.vue', import.meta.url)

test('gateway settings dialog declares the policy settings UI contract', async () => {
  const source = await readFile(componentPath, 'utf8')

  assert.match(source, /import \{ computed, reactive, watch \} from 'vue'/)
  assert.match(source, /import type \{ GatewaySettingsData \} from '\.\.\/\.\.\/types'/)
  assert.match(source, /const open = defineModel<boolean>\('open'/)
  assert.match(source, /form: GatewaySettingsData/)
  assert.match(source, /loading: boolean/)
  assert.match(source, /save: \[form: GatewaySettingsData\]/)
  assert.match(source, /const localForm = reactive<GatewaySettingsData>\(\{ \.\.\.props\.form \}\)/)
  assert.match(source, /buildGatewaySelectedStrategyDescriptions\(localForm\)/)
  assert.match(source, /buildGatewayStrategyDescriptionItems\(localForm\)/)
  assert.match(source, /Object\.assign\(localForm, value\)/)
  assert.match(source, /emit\('save', \{ \.\.\.localForm \}\)/)
  assert.match(source, /<a-modal/)
  assert.match(source, /v-model:open="open"/)
  assert.match(source, /title="网关策略"/)
  assert.match(source, /width="980px"/)
  assert.match(source, /:confirm-loading="loading"/)
  assert.match(source, /@ok="handleSave"/)
  assert.match(source, /<a-form layout="vertical">/)
  assert.match(source, /class="gateway-policy-settings-layout"/)
  assert.match(source, /v-model:value="localForm\.route_strategy"/)
  assert.match(source, /gatewayRouteStrategyOptions\.map/)
  assert.match(source, /selectedStrategyDescriptions\.routeStrategy/)
  assert.match(source, /v-model:value="localForm\.max_attempts"/)
  assert.match(source, /v-model:value="localForm\.failure_threshold"/)
  assert.match(source, /v-model:value="localForm\.cooldown_seconds"/)
  assert.match(source, /v-model:value="localForm\.request_timeout"/)
  assert.match(source, /v-model:value="localForm\.failure_retry_mode"/)
  assert.match(source, /gatewayFailureRetryModeOptions\.map/)
  assert.match(source, /v-model:value="localForm\.route_concurrency_limit"/)
  assert.match(source, /v-model:value="localForm\.concurrency_transfer_strategy"/)
  assert.match(source, /gatewayConcurrencyTransferOptions\.map/)
  assert.match(source, /v-model:value="localForm\.concurrency_overflow_strategy"/)
  assert.match(source, /gatewayOverflowStrategyOptions\.map/)
  assert.match(source, /message="策略关系"/)
  assert.match(source, /v-if="localForm\.route_strategy === 'smart'"/)
  assert.match(source, /v-model:value="localForm\.smart_latency_bias"/)
  assert.match(source, /v-model:value="localForm\.smart_concurrency_bias"/)
  assert.match(source, /v-model:value="localForm\.smart_failure_bias"/)
  assert.match(source, /v-model:value="localForm\.smart_priority_bias"/)
  assert.match(source, /v-model:value="localForm\.gateway_api_key"/)
  assert.match(source, /placeholder="用于 cc-switch \/ OpenAI 客户端请求网关的 Bearer Key"/)
  assert.match(source, /v-for="item in gatewayRouteStrategyOptions"/)
  assert.match(source, /'gateway-policy-help__item--active': item\.value === localForm\.route_strategy/)
  assert.match(source, /v-for="item in gatewayStrategyDescriptionItems"/)
})

test('GatewayOverlayHost delegates gateway settings dialog rendering to the component boundary', async () => {
  const source = await readFile(hostPath, 'utf8')

  assert.match(source, /import GatewaySettingsDialog from '\.\/GatewaySettingsDialog\.vue'/)
  assert.match(source, /<GatewaySettingsDialog/)
  assert.match(source, /v-model:open="settingsOpen"/)
  assert.match(source, /:form="settingsForm"/)
  assert.match(source, /:loading="settingsLoading"/)
  assert.match(source, /@save="emit\('settings-save', \$event\)"/)
  assert.doesNotMatch(source, /<a-modal\s+v-model:open="settingsOpen"/)
  assert.doesNotMatch(source, /gateway-policy-settings-layout/)
  assert.doesNotMatch(source, /settingsForm\.smart_latency_bias/)
})
