import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const componentPath = new URL('../src/components/gateway/GatewayOverlayHost.vue', import.meta.url)
const pageHostPath = new URL('../src/components/gateway/GatewayOverlayPageHost.vue', import.meta.url)
const shellPath = new URL('../src/components/gateway/GatewayPageShell.vue', import.meta.url)
const viewPath = new URL('../src/views/GatewayView.vue', import.meta.url)
const gatewayViewPath = viewPath
const gatewayPageControllerPath = new URL('../src/gatewayPageController.ts', import.meta.url)
const shellBindingsControllerPath = new URL('../src/gatewayPageShellBindingsController.ts', import.meta.url)
const pageBindingsControllerPath = new URL('../src/gatewayPageBindingsController.ts', import.meta.url)

test('gateway overlay host declares the dialog and drawer wiring contract', async () => {
  const source = await readFile(componentPath, 'utf8')

  assert.match(source, /const priorityOpen = defineModel<boolean>\('priorityOpen'/)
  assert.match(source, /const priorityInsertIndex = defineModel<number \| undefined>\('priorityInsertIndex'/)
  assert.match(source, /const balanceProbeManualOpen = defineModel<boolean>\('balanceProbeManualOpen'/)
  assert.match(source, /const balanceProbeManualURL = defineModel<string>\('balanceProbeManualURL'/)
  assert.match(source, /const settingsOpen = defineModel<boolean>\('settingsOpen'/)
  assert.match(source, /const addUpstreamOpen = defineModel<boolean>\('addUpstreamOpen'/)
  assert.match(source, /const addUpstreamGroupNames = defineModel<string\[\]>\('addUpstreamGroupNames'/)
  assert.match(source, /const routeGroupManagerOpen = defineModel<boolean>\('routeGroupManagerOpen'/)
  assert.match(source, /const routeGroupAssignmentOpen = defineModel<boolean>\('routeGroupAssignmentOpen'/)
  assert.match(source, /const routeGroupAssignmentIds = defineModel<number\[\]>\('routeGroupAssignmentIds'/)
  assert.match(source, /const routeModelsOpen = defineModel<boolean>\('routeModelsOpen'/)
  assert.match(source, /const routeModelsRequestUrls = defineModel<string>\('routeModelsRequestUrls'/)
  assert.match(source, /const routeModelsSupportedModels = defineModel<string\[\]>\('routeModelsSupportedModels'/)
  assert.match(source, /const logsDrawerOpen = defineModel<boolean>\('logsDrawerOpen'/)
  assert.match(source, /const logSearch = defineModel<string>\('logSearch'/)
  assert.match(source, /const routeLogsDrawerOpen = defineModel<boolean>\('routeLogsDrawerOpen'/)
  assert.match(source, /const routeLogSearch = defineModel<string>\('routeLogSearch'/)
  assert.match(source, /const routeDiagnosisOpen = defineModel<boolean>\('routeDiagnosisOpen'/)
  assert.match(source, /priorityColumns: ColumnsType<GatewayRoute>/)
  assert.match(source, /settingsForm: GatewaySettingsData/)
  assert.match(source, /addUpstreamForm: AddUpstreamForm/)
  assert.match(source, /logColumns: ColumnsType<GatewayLog>/)
  assert.match(source, /routeLogsTitle: string/)
  assert.match(source, /routeDiagnosis: GatewayRouteDiagnosisView \| null/)
  assert.match(source, /event: 'priority-move'/)
  assert.match(source, /event: 'priority-preset'/)
  assert.match(source, /event: 'balance-submit'/)
  assert.match(source, /event: 'settings-save'/)
  assert.match(source, /event: 'add-upstream-submit'/)
  assert.match(source, /event: 'add-upstream-reset'/)
  assert.match(source, /event: 'route-groups-refresh'/)
  assert.match(source, /event: 'route-group-create'/)
  assert.match(source, /event: 'route-group-update'/)
  assert.match(source, /event: 'route-group-delete'/)
  assert.match(source, /event: 'route-group-assignment-save'/)
  assert.match(source, /event: 'route-models-save'/)
  assert.match(source, /<GatewayPriorityDialog/)
  assert.match(source, /<GatewayRouteBalanceManualDialog/)
  assert.match(source, /<GatewaySettingsDialog/)
  assert.match(source, /<GatewayAddUpstreamDialog/)
  assert.match(source, /<GatewayRouteGroupsDialog/)
  assert.match(source, /<GatewayRouteGroupAssignmentDialog/)
  assert.match(source, /<GatewayRouteModelsDialog/)
  assert.match(source, /<GatewayRouteDiagnosisDrawer/)
  assert.equal((source.match(/<GatewayLogsDrawer/g) ?? []).length, 2)
})

test('GatewayOverlayPageHost delegates overlay rendering to the host component boundary', async () => {
  const source = await readFile(pageHostPath, 'utf8')

  assert.match(source, /import GatewayOverlayHost from '\.\/GatewayOverlayHost\.vue'/)
  assert.match(source, /<GatewayOverlayHost/)
  assert.match(source, /v-model:priority-open="priorityOpen"/)
  assert.match(source, /v-model:balance-probe-manual-open="balanceManualOpen"/)
  assert.match(source, /v-model:route-group-manager-open="routeGroupManagerOpen"/)
  assert.match(source, /v-model:route-group-assignment-open="routeGroupAssignmentOpen"/)
  assert.match(source, /v-model:route-group-assignment-ids="routeGroupAssignmentIds"/)
  assert.match(source, /v-model:route-models-request-urls="routeModelsRequestURLs"/)
  assert.match(source, /v-model:logs-drawer-open="logsDrawerOpen"/)
  assert.match(source, /:route-logs-title="routeLogsTitle"/)
  assert.match(source, /@priority-move="emit\('priority-move'\)"/)
  assert.match(source, /@priority-preset="emit\('priority-preset', \$event\)"/)
  assert.match(source, /@balance-submit="emit\('balance-submit'\)"/)
  assert.match(source, /@settings-save="emit\('settings-save', \$event\)"/)
  assert.match(source, /@add-upstream-submit="\(form, selectedGroupNames\) => emit\('add-upstream-submit', form, selectedGroupNames\)"/)
  assert.match(source, /@add-upstream-reset="emit\('add-upstream-reset'\)"/)
  assert.match(source, /@route-groups-refresh="emit\('route-groups-refresh'\)"/)
  assert.match(source, /@route-group-create="emit\('route-group-create', \$event\)"/)
  assert.match(source, /@route-group-update="\(group, payload\) => emit\('route-group-update', group, payload\)"/)
  assert.match(source, /@route-group-delete="emit\('route-group-delete', \$event\)"/)
  assert.match(source, /@route-group-assignment-save="emit\('route-group-assignment-save'\)"/)
  assert.match(source, /@route-models-save="emit\('route-models-save'\)"/)
  assert.doesNotMatch(source, /<GatewayPriorityDialog/)
  assert.doesNotMatch(source, /<GatewayRouteBalanceManualDialog/)
  assert.doesNotMatch(source, /<GatewaySettingsDialog/)
  assert.doesNotMatch(source, /<GatewayAddUpstreamDialog/)
  assert.doesNotMatch(source, /<GatewayRouteGroupsDialog/)
  assert.doesNotMatch(source, /<GatewayRouteGroupAssignmentDialog/)
  assert.doesNotMatch(source, /<GatewayRouteModelsDialog/)
  assert.doesNotMatch(source, /<GatewayLogsDrawer/)
  assert.doesNotMatch(source, /<GatewayRouteDiagnosisDrawer/)
})

test('GatewayView delegates overlay page wiring to the page host boundary', async () => {
  const viewSource = await readFile(gatewayViewPath, 'utf8')
  const pageControllerSource = await readFile(gatewayPageControllerPath, 'utf8')
  const shellBindingsControllerSource = await readFile(shellBindingsControllerPath, 'utf8')

  assert.match(viewSource, /useGatewayPageController\(\{/)
  assert.doesNotMatch(viewSource, /useGatewayPageState\(\)/)
  assert.doesNotMatch(viewSource, /useGatewayRuntimeOperationsPageActions\(\{/)
  assert.doesNotMatch(viewSource, /useGatewayRouteManagementOperationsPageActions\(\{/)
  assert.doesNotMatch(viewSource, /useGatewayAdminOperationsPageActions\(\{/)
  assert.ok(shellBindingsControllerSource.includes("useGatewayPageBindings"), "GatewayView delegates overlay page wiring to the page host boundary should keep useGatewayPageBindings in gateway page controller")
  assert.ok(pageControllerSource.includes("overlayPageProps"), "GatewayView delegates overlay page wiring to the page host boundary should keep overlayPageProps in gateway page controller")
})
