import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const componentPath = new URL('../src/components/gateway/GatewayAddUpstreamDialog.vue', import.meta.url)
const hostPath = new URL('../src/components/gateway/GatewayOverlayHost.vue', import.meta.url)

test('gateway add upstream dialog declares the api-supplier form UI contract', async () => {
  const source = await readFile(componentPath, 'utf8')

  assert.match(source, /import \{ reactive, ref, watch \} from 'vue'/)
  assert.match(source, /import type \{ AddUpstreamForm \} from '\.\.\/(?:\.\.\/|\.\/)gatewayAddUpstreamModel'/)
  assert.match(source, /const open = defineModel<boolean>\('open'/)
  assert.match(source, /const groupNames = defineModel<string\[\]>\('groupNames'/)
  assert.match(source, /form: AddUpstreamForm/)
  assert.match(source, /groupOptions: SelectOption\[\]/)
  assert.match(source, /loading: boolean/)
  assert.match(source, /submit: \[form: AddUpstreamForm, groupNames: string\[\]\]/)
  assert.match(source, /reset: \[\]/)
  assert.match(source, /const localForm = reactive<AddUpstreamForm>\(\{ \.\.\.props\.form \}\)/)
  assert.match(source, /const localGroupNames = ref\(\[\.\.\.groupNames\.value\]\)/)
  assert.match(source, /Object\.assign\(localForm, value\)/)
  assert.match(source, /watch\(open, \(value\) => \{/)
  assert.match(source, /if \(value\) \{/)
  assert.doesNotMatch(source, /watch\(groupNames,/)
  assert.match(source, /emit\('submit', \{ \.\.\.localForm \}, \[\.\.\.localGroupNames\.value\]\)/)
  assert.match(source, /apiFormatOptions/)
  assert.match(source, /<a-modal/)
  assert.match(source, /v-model:open="open"/)
  assert.match(source, /title="添加上游 \(api-supplier\)"/)
  assert.match(source, /:confirm-loading="loading"/)
  assert.match(source, /ok-text="保存并加入路由池"/)
  assert.match(source, /cancel-text="取消"/)
  assert.match(source, /width="640px"/)
  assert.match(source, /@ok="handleSubmit"/)
  assert.match(source, /@cancel="handleCancel"/)
  assert.match(source, /message="该上游仅参与网关转发，不参与签到 \/ 同步。"/)
  assert.match(source, /<a-form layout="vertical">/)
  assert.match(source, /v-model:value="localForm\.name"/)
  assert.match(source, /placeholder="便于识别，例如 acme-anthropic-1"/)
  assert.match(source, /v-model:value="localForm\.api_format"/)
  assert.match(source, /:options="apiFormatOptions"/)
  assert.match(source, /v-model:value="localForm\.base_url"/)
  assert.match(source, /placeholder="https:\/\/example\.com 或 https:\/\/example\.com\/v1"/)
  assert.match(source, /v-model:value="localForm\.api_key"/)
  assert.match(source, /placeholder="sk-\.\.\."/)
  assert.match(source, /v-model:value="localGroupNames"/)
  assert.match(source, /mode="multiple"/)
  assert.match(source, /:options="groupOptions"/)
  assert.match(source, /:max-tag-count="4"/)
  assert.match(source, /v-model:value="localForm\.preferred_model"/)
  assert.match(source, /placeholder="claude-sonnet-4-6 \/ gemini-2\.5-pro"/)
  assert.match(source, /v-model:value="localForm\.supported_models"/)
  assert.match(source, /mode="tags"/)
  assert.match(source, /:token-separators="\[',', '，', '\\n', '\\t'\]"/)
})

test('GatewayOverlayHost delegates add upstream dialog rendering to the component boundary', async () => {
  const source = await readFile(hostPath, 'utf8')

  assert.match(source, /import GatewayAddUpstreamDialog from '\.\/GatewayAddUpstreamDialog\.vue'/)
  assert.match(source, /<GatewayAddUpstreamDialog/)
  assert.match(source, /v-model:open="addUpstreamOpen"/)
  assert.match(source, /v-model:group-names="addUpstreamGroupNames"/)
  assert.match(source, /:form="addUpstreamForm"/)
  assert.match(source, /:group-options="groupOptions"/)
  assert.match(source, /:loading="addUpstreamLoading"/)
  assert.match(source, /@submit="\(form, selectedGroupNames\) => emit\('add-upstream-submit', form, selectedGroupNames\)"/)
  assert.match(source, /@reset="emit\('add-upstream-reset'\)"/)
  assert.doesNotMatch(source, /<a-modal\s+v-model:open="addUpstreamOpen"/)
  assert.doesNotMatch(source, /添加上游 \(api-supplier\)/)
  assert.doesNotMatch(source, /addUpstreamForm\.preferred_model/)
})
