import {
  createSite,
  createGatewayRouteGroup,
  deleteGatewayRoute,
  deleteGatewayRouteGroup,
  diagnoseGatewayRoute,
  disableAllGatewayRoutes,
  enableOnlyGatewayRoute,
  getGatewayActiveRequests,
  getGatewayLogs,
  getGatewayOverview,
  getGatewayRouteGroups,
  getGatewayRouteLogs,
  getGatewayRoutes,
  getGatewaySettings,
  getGatewayUsage,
  getSiteGroups,
  isAbortError,
  probeGatewayRoute,
  probeGatewayRouteBalance,
  probeGatewayRoutes,
  refreshSiteSummaries,
  reorderGatewayRoutePriorities,
  resetGatewayRouteCircuit,
  syncGatewayRoutes,
  toggleGatewayRoute,
  updateGatewayRouteGroup,
  updateGatewayRouteGroups,
  updateGatewayRouteType,
  updateGatewaySettings,
} from './api.ts'

export function createGatewayPageRequests() {
  return {
    createSite,
    createGatewayRouteGroup,
    deleteGatewayRoute,
    deleteGatewayRouteGroup,
    diagnoseGatewayRoute,
    disableAllGatewayRoutes,
    enableOnlyGatewayRoute,
    getGatewayActiveRequests,
    getGatewayLogs,
    getGatewayOverview,
    getGatewayRouteGroups,
    getGatewayRouteLogs,
    getGatewayRoutes,
    getGatewaySettings,
    getGatewayUsage,
    getSiteGroups,
    isAbortError,
    probeGatewayRoute,
    probeGatewayRouteBalance,
    probeGatewayRoutes,
    refreshSiteSummaries,
    reorderGatewayRoutePriorities,
    resetGatewayRouteCircuit,
    syncGatewayRoutes,
    toggleGatewayRoute,
    updateGatewayRouteGroup,
    updateGatewayRouteGroups,
    updateGatewayRouteType,
    updateGatewaySettings,
  }
}

export type GatewayPageRequests = ReturnType<typeof createGatewayPageRequests>
