import { formatGroupNames } from './format.ts'
import {
  activeRequestTransferLines,
  buildActiveErrorDetail,
  buildLogErrorDetail,
  gatewayActivityHasErrorDetail,
  gatewayLogRowKey,
  gatewayLogHasErrorDetail,
  logMethodLabel,
  logModelMeta,
  logRequestLabel,
  logRequestURL,
  logRouteLabel,
  logRouteMeta,
  logTransferLines,
  logUserAgent,
  requestMethodColor,
} from './gatewayActivityDisplayModel.ts'
import {
  asGatewayRoute,
  balanceClass,
  formatLatency,
  formatUSD,
  gatewayRouteRowKey,
  latencyClass,
  loadRouteLabel,
  normalizeGatewayRoute,
  normalizeRoutePath,
  primaryLatency,
  routeDetailItems,
  routeErrorDetails,
  routeIssueLabels,
  routeLatencyDetails,
  routePathLabel,
  routePriorityLabel,
  routeTypeLabel,
  usageRouteLabel,
  usageRouteMeta,
  usageRowKey,
} from './gatewayRouteDisplayModel.ts'
import { formatNumber, supportedModelsPreview } from './viewUtils.ts'

export function createGatewayPageDisplayHelpers() {
  return {
    formatGroupNames,
    formatNumber,
    supportedModelsPreview,
    asRoute: asGatewayRoute,
    balanceClass,
    formatLatency,
    formatUSD,
    rowKey: gatewayRouteRowKey,
    routeRowKey: gatewayRouteRowKey,
    latencyClass,
    loadRouteLabel,
    normalizeGatewayRoute,
    normalizeRoutePath,
    primaryLatency,
    routeDetailItems,
    routeErrorDetails,
    routeIssueLabels,
    routeLatencyDetails,
    routePathLabel,
    routePriorityLabel,
    routeTypeLabel,
    usageRouteLabel,
    usageRouteMeta,
    usageRowKey,
    logRowKey: gatewayLogRowKey,
    logMethodLabel,
    logModelMeta,
    logRequestLabel,
    logRequestURL,
    logRouteLabel,
    logRouteMeta,
    logTransferLines,
    activeRequestTransferLines,
    gatewayActivityHasErrorDetail,
    gatewayLogHasErrorDetail,
    buildLogErrorDetail,
    buildActiveErrorDetail,
    logUserAgent,
    requestMethodColor,
  }
}

export type GatewayPageDisplayHelpers = ReturnType<typeof createGatewayPageDisplayHelpers>
